name: TCC - CI

on: 

  push:
    branches: [main]
    
  workflow_dispatch:

jobs:

  test:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install dependencies
        run: npm install
        continue-on-error: true
      - name: Run api tests on jest
        run: npm run testAPI
        continue-on-error: true
      - name: Run UI tests and contracts tests on cypress
        run: npm run cy:run
        continue-on-error: true
      - name: Publish Report Cypress
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
      
      
